import type { NextPage } from "next"
import Head from "next/head"

import Button from "@mui/material/Button"

import * as styles from "../styles/homepage.css"
import { Div } from "../components/Div"
import Box from "@mui/material/Box"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button variant="contained">My button</Button>

      <Box
        sx={{
          display: (theme) => {
            console.log(theme)
            return "block"
          },
        }}
      ></Box>

      <div className={styles.sstyle}>This is somethign else</div>

      <Div background="cerulean5" color="white" paddingY={4}>
        test
      </Div>
    </div>
  )
}

export default Home
