import type { NextPage } from "next"
import Head from "next/head"

import Button from "@mui/material/Button"

import * as styles from "@styles/homepage.css"
import { Div } from "@components/Div"
import Box from "@mui/material/Box"
import { Page } from "@components/Page"
import Link from "next/link"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page>
        <Box
          sx={{
            display: (theme) => {
              console.log(theme)
              return "block"
            },
          }}
        ></Box>
        <Div component="ul" padding={6}>
          <li>
            <Link href="/validate-number">
              <a>Validate Number</a>
            </Link>
          </li>
          <li>
            <Link href="/step1">
              <a>Care selection</a>
            </Link>
          </li>
        </Div>
      </Page>
    </div>
  )
}

export default Home
