import { Card, CardActionArea, CardContent, Grid, Stack } from "@mui/material"
import Grid2 from "@mui/material/Unstable_Grid2"
import { Container } from "@mui/system"
import type { NextPage } from "next"
import Head from "next/head"
import { Div } from "@components/Div"
import { Text } from "@components/Text"

import * as styles from "@styles/pages/step1.css"
import { Header } from "@templates/Header"
import { MainCta } from "@components/MainCta"
import { Page } from "@components/Page"
import { BackButton } from "@components/BackButton/BackButton"
import { useState } from "react"
import { CardPicker } from "@components/CardPicker"

const Home: NextPage = () => {
  const [selectedCard, setSelectedCard] = useState('')

  return (
    <>
      <Head>
        <title>First, when do you need care</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#FCFAF5" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page>
        <Header></Header>

        <Container maxWidth="sm">
          <Div paddingX={{ md: 6 }} paddingY={6}>
            <Stack spacing={3}>
              <Text
                font="heading"
                variant="h2"
                color="black"
                textAlign="center"
              >
                First, when do you need care?
              </Text>

              <CardPicker>
                {({selectedCard, setSelectedCard}) => {
                  const getClassName = (card: string) => {
                    if (selectedCard) {
                      return selectedCard === card
                        ? styles.cardSelected
                        : styles.cardFaded
                    } else {
                      return styles.cardResting
                    }
                  }
                  return (
                    <Grid2 container spacing={3}>
                      <Grid2 xs={12} sm={6}>
                        <Card className={getClassName("first")}>
                          <CardActionArea
                            value="first"
                            onClick={() => setSelectedCard("first")}
                          >
                            <CardContent>
                              <Text variant="subheading2">Right away</Text>
                            </CardContent>
                          </CardActionArea>
                        </Card>
                      </Grid2>
                      <Grid2 xs={12} sm={6}>
                        <Card className={getClassName("second")}>
                          <CardActionArea
                            value="second"
                            onClick={() => setSelectedCard("second")}
                          >
                            <CardContent>
                              <Text variant="subheading2">Im flexible</Text>
                            </CardContent>
                          </CardActionArea>
                        </Card>
                      </Grid2>
                    </Grid2>
                  )
                }}
              </CardPicker>
            </Stack>
            <Div
              justifyContent="space-between"
              paddingY={5}
              gap={3}
              display="flex"
            >
              <BackButton />
              <MainCta disabled={!selectedCard} />
            </Div>
          </Div>
        </Container>
      </Page>
    </>
  )
}

export default Home
