import { Card, CardActionArea, CardContent, Grid, Stack } from "@mui/material"
import Grid2 from "@mui/material/Unstable_Grid2"
import { Container } from "@mui/system"
import type { NextPage } from "next"
import Head from "next/head"
import { useForm, Controller } from "react-hook-form"
import { Div } from "@components/Div"
import { Text } from "@components/Text"

import * as styles from "@styles/pages/step1.css"
import { Header } from "@templates/Header"
import { MainCta } from "@components/MainCta"
import { Page } from "@components/Page"
import { BackButton } from "@components/BackButton/BackButton"
import { useRouter } from "next/router"

const Home: NextPage = () => {
  const router = useRouter()
  const {
    handleSubmit,
    control,
    formState: { isValid },
  } = useForm({
    defaultValues: {
      careTime: "",
    },
    mode: "onChange",
  })
  const submit = (data: any) => {
    console.log(data)
    router.push("/step2")
  }

  return (
    <>
      <Head>
        <title>First, when do you need care</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#FCFAF5" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page>
        <Header></Header>
        <Container maxWidth="sm">
          <Div
            component="form"
            paddingX={{ md: 6 }}
            paddingY={6}
            onSubmit={handleSubmit(submit)}
          >
            <Stack spacing={3}>
              <Text
                font="heading"
                variant="h2"
                color="black"
                textAlign="center"
              >
                First, when do you need care?
              </Text>

              <Controller
                name="careTime"
                control={control}
                rules={{ required: true }}
                render={({ field }) => {
                  const { onChange, value } = field
                  const getClassName = (card: string) => {
                    if (value) {
                      return value === card
                        ? styles.cardSelected
                        : styles.cardFaded
                    } else {
                      return styles.cardResting
                    }
                  }
                  return (
                    <Grid2 container spacing={3}>
                      <Grid2 xs={12} sm={6}>
                        <Card className={getClassName("now")}>
                          <CardActionArea onClick={() => onChange("now")}>
                            <CardContent>
                              <Text variant="subheading2">Right away</Text>
                            </CardContent>
                          </CardActionArea>
                        </Card>
                      </Grid2>
                      <Grid2 xs={12} sm={6}>
                        <Card className={getClassName("later")}>
                          <CardActionArea onClick={() => onChange("later")}>
                            <CardContent>
                              <Text variant="subheading2">Im flexible</Text>
                            </CardContent>
                          </CardActionArea>
                        </Card>
                      </Grid2>
                    </Grid2>
                  )
                }}
              />
            </Stack>
            <Div
              justifyContent="space-between"
              paddingY={5}
              gap={3}
              display="flex"
            >
              <BackButton href="/validate-number" />
              <MainCta type="submit" disabled={!isValid} />
            </Div>
          </Div>
        </Container>
      </Page>
    </>
  )
}

export default Home
