import {
  Button,
  Card,
  CardActionArea,
  CardContent,
  Slider,
  Stack,
} from "@mui/material"
import Grid2 from "@mui/material/Unstable_Grid2"
import { Container } from "@mui/system"
import type { NextPage } from "next"
import Head from "next/head"
import { useForm, Controller } from "react-hook-form"
import { Div } from "@components/Div"
import { Text } from "@components/Text"

import { Header } from "@templates/Header"
import { MainCta } from "@components/MainCta"
import { Page } from "@components/Page"
import { BackButton } from "@components/BackButton/BackButton"
import { CardOption } from "@components/CardOption/CardOption"
import { useState } from "react"

type FormData = {
  budget: Array<number>
  gender: string
  language: Array<string>
  driving: Array<string>
  other: Array<string>
}

const Home: NextPage = () => {
  const [isLangExpanded, setLangExpanded] = useState(false)
  const {
    handleSubmit,
    control,
    formState: { isValid },
  } = useForm<FormData>({
    defaultValues: {
      budget: [20, 60],
      gender: "",
      language: [],
      driving: [],
      other: [],
    },
    mode: "onChange",
  })
  const submit = (data: any) => {
    console.log(data)
  }

  return (
    <>
      <Head>
        <title>First, when do you need care</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#FCFAF5" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page>
        <Header></Header>
        <Container maxWidth="sm">
          <Div
            component="form"
            paddingX={{ md: 6 }}
            paddingY={6}
            onSubmit={handleSubmit(submit)}
          >
            <Stack spacing={3}>
              <Text
                font="heading"
                variant="h2"
                color="black"
                textAlign="center"
              >
                Next, let’s find your ideal caregiver
              </Text>

              <Card>
                <CardContent>
                  <Grid2 container>
                    <Grid2 xs={12} md={5}>
                      <Text
                        variant="subheading2"
                        marginBottom={4}
                        marginTop={2}
                      >
                        Whats your budget?
                      </Text>
                    </Grid2>
                    <Grid2 xs={12} md={7}>
                      <Controller
                        name="budget"
                        control={control}
                        render={({ field }) => (
                          <Div paddingTop={6}>
                            <Slider
                              value={field.value}
                              valueLabelDisplay="on"
                              valueLabelFormat={(v) => `$${v}/h`}
                              onChange={(event, newValue) =>
                                field.onChange(newValue)
                              }
                            />
                            <Text
                              variant="body2"
                              background="cerulean1"
                              color="cerulean8"
                              textAlign="center"
                              padding={3}
                              borderRadius="large"
                              marginTop={2}
                            >
                              This is a typical price range for services in your
                              area
                            </Text>
                          </Div>
                        )}
                      />
                    </Grid2>
                  </Grid2>
                </CardContent>
              </Card>

              <Card>
                <CardContent>
                  <Grid2 container>
                    <Grid2 xs={12} md={5}>
                      <Text
                        variant="subheading2"
                        marginBottom={4}
                        marginTop={2}
                      >
                        Gender preference
                      </Text>
                    </Grid2>
                    <Grid2 xs={12} md={7}>
                      <Controller
                        name="gender"
                        control={control}
                        rules={{ required: true }}
                        render={({ field }) => {
                          const { onChange, value } = field
                          return (
                            <Div
                              display="grid"
                              gap={2}
                              style={{
                                gridTemplateColumns: "repeat(2, 1fr)",
                              }}
                            >
                              <CardOption
                                label="Male"
                                selected={value === "male"}
                                onClick={() => onChange("male")}
                              />
                              <CardOption
                                label="Female"
                                selected={value === "female"}
                                onClick={() => onChange("female")}
                              />
                              <Div gridColumn="span 2">
                                <CardOption
                                  label="No Preference"
                                  selected={value === "none"}
                                  onClick={() => onChange("none")}
                                />
                              </Div>
                            </Div>
                          )
                        }}
                      />
                    </Grid2>
                  </Grid2>
                </CardContent>
              </Card>

              <Card>
                <CardContent>
                  <Grid2 container>
                    <Grid2 xs={12} md={5}>
                      <Text
                        variant="subheading2"
                        marginBottom={4}
                        marginTop={2}
                      >
                        Languages spoken
                      </Text>
                    </Grid2>
                    <Grid2 xs={12} md={7}>
                      <Controller
                        name="language"
                        control={control}
                        rules={{ required: true }}
                        render={({ field }) => {
                          const { onChange, value } = field
                          const toggleValue = (val: string) => {
                            const isChecked = value.indexOf(val) !== -1
                            const newValue = isChecked
                              ? value.filter((x) => x !== val)
                              : value.concat([val])
                            onChange(newValue)
                          }
                          return (
                            <>
                              <Div
                                display="grid"
                                gap={2}
                                style={{
                                  gridTemplateColumns: "repeat(2, 1fr)",
                                }}
                              >
                                <CardOption
                                  label="English"
                                  selected={value.includes("english")}
                                  onClick={() => toggleValue("english")}
                                />
                                <CardOption
                                  label="Spanish"
                                  selected={value.includes("spanish")}
                                  onClick={() => toggleValue("spanish")}
                                />
                                <CardOption
                                  label="Mandarin"
                                  selected={value.includes("mandarin")}
                                  onClick={() => toggleValue("mandarin")}
                                />
                                <CardOption
                                  label="Cantonese"
                                  selected={value.includes("cantonese")}
                                  onClick={() => toggleValue("cantonese")}
                                />
                                <CardOption
                                  label="Tagalog"
                                  selected={value.includes("tagalog")}
                                  onClick={() => toggleValue("tagalog")}
                                />
                                <CardOption
                                  label="Vietnamese"
                                  selected={value.includes("vietnamese")}
                                  onClick={() => toggleValue("vietnamese")}
                                />
                                {isLangExpanded && (
                                  <>
                                    <CardOption
                                      label="Another"
                                      selected={value.includes("another")}
                                      onClick={() => toggleValue("another")}
                                    />
                                    <CardOption
                                      label="Something"
                                      selected={value.includes("something")}
                                      onClick={() => toggleValue("something")}
                                    />
                                  </>
                                )}
                              </Div>
                              {!isLangExpanded && (
                                <Div paddingTop={2}>
                                  <Button
                                    variant="outlined"
                                    fullWidth
                                    onClick={() => setLangExpanded(true)}
                                  >
                                    Show more
                                  </Button>
                                </Div>
                              )}
                            </>
                          )
                        }}
                      />
                    </Grid2>
                  </Grid2>
                </CardContent>
              </Card>

              <Card>
                <CardContent>
                  <Grid2 container>
                    <Grid2 xs={12} md={5}>
                      <Text
                        variant="subheading2"
                        marginBottom={4}
                        marginTop={2}
                      >
                        Driving requirements
                      </Text>
                    </Grid2>
                    <Grid2 xs={12} md={7}>
                      <Controller
                        name="driving"
                        control={control}
                        rules={{ required: true }}
                        render={({ field }) => {
                          const { onChange, value } = field
                          const toggleValue = (val: string) => {
                            const isChecked = value.indexOf(val) !== -1
                            const newValue = isChecked
                              ? value.filter((x) => x !== val)
                              : value.concat([val])
                            onChange(newValue)
                          }
                          return (
                            <>
                              <Div
                                display="grid"
                                gap={2}
                                style={{
                                  gridTemplateColumns: "repeat(2, 1fr)",
                                }}
                              >
                                <CardOption
                                  label="Valid License"
                                  selected={value.includes("valid_license")}
                                  onClick={() => toggleValue("valid_license")}
                                />
                                <CardOption
                                  label="Insured"
                                  selected={value.includes("insured")}
                                  onClick={() => toggleValue("insured")}
                                />
                                <Div gridColumn="span 2">
                                  <CardOption
                                    label="Has Own Car"
                                    selected={value.includes("has_car")}
                                    onClick={() => toggleValue("has_car")}
                                  />
                                </Div>
                              </Div>
                            </>
                          )
                        }}
                      />
                    </Grid2>
                  </Grid2>
                </CardContent>
              </Card>

              <Card>
                <CardContent>
                  <Grid2 container>
                    <Grid2 xs={12} md={5}>
                      <Text
                        variant="subheading2"
                        marginBottom={4}
                        marginTop={2}
                      >
                        Any other needs
                      </Text>
                    </Grid2>
                    <Grid2 xs={12} md={7}>
                      <Controller
                        name="other"
                        control={control}
                        render={({ field }) => {
                          const { onChange, value } = field
                          const toggleValue = (val: string) => {
                            const isChecked = value.indexOf(val) !== -1
                            const newValue = isChecked
                              ? value.filter((x) => x !== val)
                              : value.concat([val])
                            onChange(newValue)
                          }
                          return (
                            <>
                              <Div
                                display="grid"
                                gap={2}
                                style={{
                                  gridTemplateColumns: "repeat(2, 1fr)",
                                }}
                              >
                                <CardOption
                                  label="Dog Friendly"
                                  selected={value.includes("dog_friendly")}
                                  onClick={() => toggleValue("dog_friendly")}
                                />
                                <CardOption
                                  label="Cat Friendly"
                                  selected={value.includes("cat_friendly")}
                                  onClick={() => toggleValue("cat_friendly")}
                                />
                                <CardOption
                                  label="Non-Smoker"
                                  selected={value.includes("non_smoker")}
                                  onClick={() => toggleValue("non_smoker")}
                                />
                                <CardOption
                                  label="Exotic Animal Friendly"
                                  selected={value.includes(
                                    "exotic_animal_friendly"
                                  )}
                                  onClick={() =>
                                    toggleValue("exotic_animal_friendly")
                                  }
                                />
                              </Div>
                            </>
                          )
                        }}
                      />
                    </Grid2>
                  </Grid2>
                </CardContent>
              </Card>
            </Stack>
            <Div
              justifyContent="space-between"
              paddingY={5}
              gap={3}
              display="flex"
            >
              <BackButton href="/step1" />
              <MainCta type="submit" disabled={!isValid} />
            </Div>
          </Div>
        </Container>
      </Page>
    </>
  )
}

export default Home
