import {
  Button,
  Card,
  CardContent,
  Grid,
  OutlinedInput,
  Stack,
} from "@mui/material"
import { Container } from "@mui/system"
import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { Div } from "../components/Div"
import { Text } from "../components/Text"

import * as styles from "../styles/pages/validate-number.css"
import { Header } from "../templates/Header"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Validate your number</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <Container maxWidth="sm" className={styles.noPaddingOnMobile}>
        <Card className={styles.mobileTransparentCard}>
          <Div position="relative" className={styles.cardMedia}>
            <Image
              alt="care"
              src="/images/care.jpg"
              objectFit="cover"
              layout="fill"
            />
          </Div>
          <Div paddingX={{ xs: 3, md: 6 }} paddingY={6}>
            <Stack spacing={3}>
              <Text
                font="heading"
                variant="h2"
                color="black"
                textAlign="center"
              >
                Ready to find care?
              </Text>
              <Text
                font="body"
                variant="subheading2"
                color="cream6"
                textAlign="center"
              >
                Enter your zip code to get started locating caregivers in your
                area.
              </Text>

              <Grid container justifyContent="center">
                <Grid item xs={12} sm={6} md={7}>
                  <Stack spacing={2}>
                    <OutlinedInput
                      fullWidth
                      placeholder="Phone *"
                      endAdornment={
                        <Text
                          font="body"
                          variant="body2"
                          color="cream5"
                          whiteSpace="nowrap"
                          pointerEvents="none"
                        >
                          Phone Number
                        </Text>
                      }
                    />

                    <OutlinedInput
                      fullWidth
                      placeholder="Zipcode *"
                      endAdornment={
                        <Text
                          font="body"
                          variant="body2"
                          color="cream5"
                          whiteSpace="nowrap"
                          pointerEvents="none"
                        >
                          e.g. 94102
                        </Text>
                      }
                    />
                  </Stack>
                </Grid>
              </Grid>
              <Text variant="body2" textAlign="center">
                <Div component="span" color="papaya5">
                  *
                </Div>{" "}
                Required to complete your profile
              </Text>
            </Stack>
          </Div>
        </Card>
        <Div
          display={{ xs: "none", sm: "flex" }}
          justifyContent="space-between"
          paddingY={5}
          gap={3}
        >
          <Button variant="outlined" className={styles.button}>
            Back
          </Button>
          <Button variant="contained" className={styles.button}>
            Next
          </Button>
        </Div>
      </Container>
    </>
  )
}

export default Home
